@startuml

left to right direction

title Coupling Component Diagram

() "Data In 1" as DI1
() "Data In 2" as DI2

package "Execution Engine" {
  component "Discipline 1" as D1
  component "Discipline 2" as D2
  component "Discipline 3" as D3
}

() "Data Out 1" as DO1
() "Data Out 2" as DO2

DI1 )-- D1
DI2 )-- D3
D1 -0)- D2
D3 -0)- D2
D2 --0 DO1
D3 --0 DO2

@enduml
