@startuml

left to right direction

title Study Component Diagram

package Study {
  database "Data In" as DI
  package "Execution Engine" {
    component "Discipline 1" as D1
    component "Discipline 2" as D2
    cloud "..." as Dots
    component "Discipline N" as DN
  }
  database "Data Out" as DO
}

DI --> D1 : data
D1 --> D2 : data
D2 --> Dots : data
Dots --> DN : data
DN --> DO : data

@enduml
